	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="<?php echo $config->urls->templates?>js/jquery-2.2.0.min.js"><\/script>')</script>
	
	<!-- build:js(src) ../js/application.min.js -->
	<script src="js/script-1.js"></script>
	<script src="js/script-2.js"></script>
	<script src="js/script-3.js"></script>
	<!-- endbuild -->

	</body>
</html>